# permissions for end users to edit o2ims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tutorial-gitops-operator
    app.kubernetes.io/managed-by: kustomize
  name: o2ims-editor-role
rules:
- apiGroups:
  - gitops.example.com
  resources:
  - o2ims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitops.example.com
  resources:
  - o2ims/status
  verbs:
  - get
